[package]
name = "foctet-http-workers-echo"
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
foctet-http = { path = "../..", features = ["workers"] }
worker = "0.8.5"
x25519-dalek = { version = "3", features = ["static_secrets"] }

[workspace]
